# Generated by Django 5.2.3 on 2025-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
