events{
    
}

http {
    server{
        listen 8080;

        location /api/auth/ {
            rewrite ^/api/auth/(.*) /api/$1 break;
            proxy_pass http://authentication-container:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root /static/html;
        }
    }
}