services: 
      authentication:
        image: authentication-image
        container_name: authentication-container
        build: .
        ports: 
            - 8000:8000
        depends_on:
            db:
              condition: 
                    service_healthy
        networks:
           - app-network

      web:
        image: nginx
        container_name: nginx-container
        ports:
          - "8080:8080"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./static/html:/static/html
        networks:
          - app-network

      db:
        image: postgres
        container_name: postgresql-container
        restart: always
        environment:
             POSTGRES_PASSWORD: ${database_password}
             POSTGRES_USER: ${database_user}
             POSTGRES_DB: ${database_name}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${database_user}"]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
          - ./pgdata:/var/lib/postgresql/data
        networks:
            - app-network

# Memcached need to add to service 

networks:
     app-network:
        driver: bridge