# Generated by Django 5.2.3 on 2025-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_productmodel_id_alter_productmodel_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
